// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt9UBaLARvALSd87faIWNycKiXRVCRjXM',
    appId: '1:80100475312:web:53fe1248974dc568781675',
    messagingSenderId: '80100475312',
    projectId: 'mobile-sms-api11',
    authDomain: 'mobile-sms-api11.firebaseapp.com',
    storageBucket: 'mobile-sms-api11.firebasestorage.app',
    measurementId: 'G-Y1WBEJZDG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpmUMZdIJAFl6QVqyH3svE8r9p6gAbPYA',
    appId: '1:80100475312:android:4c1bb1e2f0c2e4dc781675',
    messagingSenderId: '80100475312',
    projectId: 'mobile-sms-api11',
    storageBucket: 'mobile-sms-api11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_cLwkMhXcBjOHAGZXTjiZQDZlSqc-gOc',
    appId: '1:80100475312:ios:80d98232c81029f7781675',
    messagingSenderId: '80100475312',
    projectId: 'mobile-sms-api11',
    storageBucket: 'mobile-sms-api11.firebasestorage.app',
    iosBundleId: 'com.example.mobileSmsApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_cLwkMhXcBjOHAGZXTjiZQDZlSqc-gOc',
    appId: '1:80100475312:ios:80d98232c81029f7781675',
    messagingSenderId: '80100475312',
    projectId: 'mobile-sms-api11',
    storageBucket: 'mobile-sms-api11.firebasestorage.app',
    iosBundleId: 'com.example.mobileSmsApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt9UBaLARvALSd87faIWNycKiXRVCRjXM',
    appId: '1:80100475312:web:9207a631b9d25ca0781675',
    messagingSenderId: '80100475312',
    projectId: 'mobile-sms-api11',
    authDomain: 'mobile-sms-api11.firebaseapp.com',
    storageBucket: 'mobile-sms-api11.firebasestorage.app',
    measurementId: 'G-KC236ZJTV9',
  );
}
